[workspace]


members = [
    "crates/kcshared",
    "crates/kcclient",
    "crates/kcserver",
    "crates/kallichore_api",
]
resolver = "2"

[workspace.package]
rust-version = "1.75"
edition = "2021"
license = "MIT"
authors = ["Posit Software, PBC"]
