openapi: 3.0.1
info:
  contact:
    email: info@posit.co
    name: "Posit Software, PBC"
    url: https://posit.co
  description: Kallichore is a Jupyter kernel gateway and supervisor
  title: Kallichore API
  version: 1.0.0
servers:
- url: /
paths:
  /sessions:
    get:
      operationId: list-sessions
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sessionList'
          description: List of active sessions
      summary: List active sessions
    put:
      operationId: new-session
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/session'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/new_session_200_response'
          description: The session ID
      summary: Create a new session
components:
  schemas:
    session:
      properties:
        session_id:
          description: A unique identifier for the session
          type: string
        argv:
          description: The program and command-line parameters for the session
          items:
            type: string
          type: array
        working_directory:
          description: The working directory in which to start the session.
          type: string
      required:
      - argv
      - session_id
      - working_directory
      type: object
    sessionList:
      example:
        total: 0
        sessions:
        - process_id: 6
          session_id: session_id
          argv:
          - argv
          - argv
        - process_id: 6
          session_id: session_id
          argv:
          - argv
          - argv
      properties:
        total:
          type: integer
        sessions:
          items:
            $ref: '#/components/schemas/sessionList_sessions_inner'
          type: array
      required:
      - sessions
      - total
      type: object
    new_session_200_response:
      example:
        session_id: session_id
      properties:
        session_id:
          description: A unique identifier for the session
          type: string
      required:
      - session_id
      type: object
    sessionList_sessions_inner:
      example:
        process_id: 6
        session_id: session_id
        argv:
        - argv
        - argv
      properties:
        session_id:
          description: A unique identifier for the session
          type: string
        argv:
          description: The program and command-line parameters for the session
          items:
            type: string
          type: array
        process_id:
          description: "The underlying process ID of the session, if the session is\
            \ running."
          type: integer
      required:
      - argv
      - session_id
      type: object

