openapi: 3.0.1
info:
  contact:
    email: info@posit.co
    name: "Posit Software, PBC"
    url: https://posit.co
  description: Kallichore is a Jupyter kernel gateway and supervisor
  title: Kallichore API
  version: 1.0.0
servers:
- url: /
paths:
  /sessions:
    get:
      operationId: list-sessions
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sessionList'
          description: List of active sessions
      summary: List active sessions
    put:
      operationId: new-session
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/session'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/new_session_200_response'
          description: The session ID
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Invalid request
      summary: Create a new session
  /sessions/{session_id}/channels:
    get:
      operationId: channels-websocket
      parameters:
      - explode: false
        in: path
        name: session_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Upgrade connection to a websocket
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: Invalid request
      summary: Upgrade to a WebSocket for channel communication
components:
  schemas:
    error:
      example:
        code: code
        details: details
        message: message
      properties:
        code:
          type: string
        message:
          type: string
        details:
          type: string
      required:
      - code
      - message
      type: object
    status:
      description: The status of the session
      enum:
      - uninitialized
      - starting
      - idle
      - busy
      - exited
      type: string
    session:
      properties:
        session_id:
          description: A unique identifier for the session
          type: string
        username:
          description: The username of the user who owns the session
          type: string
        argv:
          description: The program and command-line parameters for the session
          items:
            type: string
          type: array
        working_directory:
          description: The working directory in which to start the session.
          type: string
        env:
          additionalProperties:
            type: string
          description: Environment variables to set for the session
          type: object
      required:
      - argv
      - env
      - session_id
      - username
      - working_directory
      type: object
    sessionList:
      example:
        total: 0
        sessions:
        - connected: true
          process_id: 6
          session_id: session_id
          started: 2000-01-23T04:56:07.000+00:00
          working_directory: working_directory
          argv:
          - argv
          - argv
          username: username
          status: uninitialized
        - connected: true
          process_id: 6
          session_id: session_id
          started: 2000-01-23T04:56:07.000+00:00
          working_directory: working_directory
          argv:
          - argv
          - argv
          username: username
          status: uninitialized
      properties:
        total:
          type: integer
        sessions:
          items:
            $ref: '#/components/schemas/sessionList_sessions_inner'
          type: array
      required:
      - sessions
      - total
      type: object
    new_session_200_response:
      example:
        session_id: session_id
      properties:
        session_id:
          description: A unique identifier for the session
          type: string
      required:
      - session_id
      type: object
    sessionList_sessions_inner:
      example:
        connected: true
        process_id: 6
        session_id: session_id
        started: 2000-01-23T04:56:07.000+00:00
        working_directory: working_directory
        argv:
        - argv
        - argv
        username: username
        status: uninitialized
      properties:
        session_id:
          description: A unique identifier for the session
          type: string
        argv:
          description: The program and command-line parameters for the session
          items:
            type: string
          type: array
        process_id:
          description: "The underlying process ID of the session, if the session is\
            \ running."
          type: integer
        username:
          description: The username of the user who owns the session
          type: string
        connected:
          description: Whether the session is connected to a client
          type: boolean
        started:
          description: An ISO 8601 timestamp of when the session was started
          format: date-time
          type: string
        working_directory:
          description: The session's current working directory
          type: string
        status:
          $ref: '#/components/schemas/status'
      required:
      - argv
      - connected
      - session_id
      - started
      - status
      - username
      - working_directory
      type: object

