[package]
name = "kcserver"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
openapi_client = { path = "../openapi_client" }
serde = { version = "1.0.203", features = ["derive"] }
swagger = "6.5.0"
futures = "0.3.30"
async-trait = "0.1.80"

