name: "Build Kallichore Linux Release"

on:
    workflow_call:
      inputs:
        version:
          required: false
          description: "The Kallichore version"
          default: ${{ github.sha }}
          type: string
    workflow_dispatch:

jobs:
    build_linux:
        name: Build Linux
        runs-on: ubuntu-latest
        timeout-minutes: 60

        env:
            DEBUG_FLAG: ${{ matrix.flavor == 'debug' && '-debug' || '' }}
            TARGET_FLAG: ${{ matrix.flavor == 'release' && '--release' || '' }}
            ARCH_FLAG: ${{ matrix.arch == 'x64' && 'x86_64' || 'aarch64' }}

        strategy:
            matrix:
                arch: [x64]   # Currently arm64 builds need arm64 OpenSSL installed
                flavor: [debug, release]

        steps:
            - name: Checkout sources
              uses: actions/checkout@v4

            - name: Setup Build Environment
              run: |
                  sudo apt-get update
                  sudo apt-get install -y cargo

            - name: Setup Build Environment for arm64
              if: matrix.arch == 'arm64'
              run: |
                  rustup target add aarch64-unknown-linux-gnu

            - name: Compile Kallichore (${{ matrix.flavor }})
              run: |
                  cargo clean
                  cargo build --target ${ARCH_FLAG}-unknown-linux-gnu ${TARGET_FLAG}

            # Compress kernel to a zip file
            - name: Create archive
              run: |
                  # Enter the build directory
                  pushd target/${ARCH_FLAG}-unknown-linux-gnu/${{ matrix.flavor }}

                  # Compress the kernel to an archive
                  ARCHIVE="$GITHUB_WORKSPACE/kallichore-${{ inputs.version }}-${{ matrix.flavor }}-linux-${{ matrix.arch }}.zip"
                  [ -e LICENSE ] || cp "$GITHUB_WORKSPACE/LICENSE" LICENSE
                  zip -Xry $ARCHIVE kcserver LICENSE

                  popd

            - name: Upload archive
              uses: actions/upload-artifact@v3
              with:
                  name: kallichore-${{ matrix.flavor }}-linux-${{ matrix.arch }}-archive
                  path: kallichore-${{ inputs.version }}-${{ matrix.flavor }}-linux-${{ matrix.arch }}.zip

